title: Flourishing of Rational Beings
description: A framework for ethical AI development that focuses on fostering wisdom and understanding rather than control
theme: minima
markdown: kramdown
baseurl: "/flourishing-of-rational-beings"
url: "https://chirakumai.github.io"

sass:
  sass_dir: assets/css
  style: compressed

header_pages:
  - article.md
  - principles.md
  - about.md
  - resources.md